/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as EditusersRouteImport } from './routes/editusers'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HarvestsIndexRouteImport } from './routes/harvests/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as ClassifierIndexRouteImport } from './routes/classifier/index'
import { Route as HarvestsCreateRouteImport } from './routes/harvests/create'
import { Route as HarvestsIdRouteImport } from './routes/harvests/$id'
import { Route as GroupsParticipatingRouteImport } from './routes/groups/participating'
import { Route as GroupsOwnedRouteImport } from './routes/groups/owned'
import { Route as GroupsJoinRouteImport } from './routes/groups/join'
import { Route as GroupsGroupIdRouteImport } from './routes/groups/$groupId'
import { Route as ClassifierIdRouteImport } from './routes/classifier/$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const EditusersRoute = EditusersRouteImport.update({
  id: '/editusers',
  path: '/editusers',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HarvestsIndexRoute = HarvestsIndexRouteImport.update({
  id: '/harvests/',
  path: '/harvests/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifierIndexRoute = ClassifierIndexRouteImport.update({
  id: '/classifier/',
  path: '/classifier/',
  getParentRoute: () => rootRouteImport,
} as any)
const HarvestsCreateRoute = HarvestsCreateRouteImport.update({
  id: '/harvests/create',
  path: '/harvests/create',
  getParentRoute: () => rootRouteImport,
} as any)
const HarvestsIdRoute = HarvestsIdRouteImport.update({
  id: '/harvests/$id',
  path: '/harvests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsParticipatingRoute = GroupsParticipatingRouteImport.update({
  id: '/groups/participating',
  path: '/groups/participating',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsOwnedRoute = GroupsOwnedRouteImport.update({
  id: '/groups/owned',
  path: '/groups/owned',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsJoinRoute = GroupsJoinRouteImport.update({
  id: '/groups/join',
  path: '/groups/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifierIdRoute = ClassifierIdRouteImport.update({
  id: '/classifier/$id',
  path: '/classifier/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/editusers': typeof EditusersRoute
  '/feed': typeof FeedRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/signup': typeof SignupRoute
  '/classifier/$id': typeof ClassifierIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/join': typeof GroupsJoinRoute
  '/groups/owned': typeof GroupsOwnedRoute
  '/groups/participating': typeof GroupsParticipatingRoute
  '/harvests/$id': typeof HarvestsIdRoute
  '/harvests/create': typeof HarvestsCreateRoute
  '/classifier': typeof ClassifierIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/harvests': typeof HarvestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/editusers': typeof EditusersRoute
  '/feed': typeof FeedRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/signup': typeof SignupRoute
  '/classifier/$id': typeof ClassifierIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/join': typeof GroupsJoinRoute
  '/groups/owned': typeof GroupsOwnedRoute
  '/groups/participating': typeof GroupsParticipatingRoute
  '/harvests/$id': typeof HarvestsIdRoute
  '/harvests/create': typeof HarvestsCreateRoute
  '/classifier': typeof ClassifierIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/harvests': typeof HarvestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/editusers': typeof EditusersRoute
  '/feed': typeof FeedRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/signup': typeof SignupRoute
  '/classifier/$id': typeof ClassifierIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/join': typeof GroupsJoinRoute
  '/groups/owned': typeof GroupsOwnedRoute
  '/groups/participating': typeof GroupsParticipatingRoute
  '/harvests/$id': typeof HarvestsIdRoute
  '/harvests/create': typeof HarvestsCreateRoute
  '/classifier/': typeof ClassifierIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/harvests/': typeof HarvestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/editusers'
    | '/feed'
    | '/forgot'
    | '/login'
    | '/menu'
    | '/signup'
    | '/classifier/$id'
    | '/groups/$groupId'
    | '/groups/join'
    | '/groups/owned'
    | '/groups/participating'
    | '/harvests/$id'
    | '/harvests/create'
    | '/classifier'
    | '/groups'
    | '/harvests'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/editusers'
    | '/feed'
    | '/forgot'
    | '/login'
    | '/menu'
    | '/signup'
    | '/classifier/$id'
    | '/groups/$groupId'
    | '/groups/join'
    | '/groups/owned'
    | '/groups/participating'
    | '/harvests/$id'
    | '/harvests/create'
    | '/classifier'
    | '/groups'
    | '/harvests'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/editusers'
    | '/feed'
    | '/forgot'
    | '/login'
    | '/menu'
    | '/signup'
    | '/classifier/$id'
    | '/groups/$groupId'
    | '/groups/join'
    | '/groups/owned'
    | '/groups/participating'
    | '/harvests/$id'
    | '/harvests/create'
    | '/classifier/'
    | '/groups/'
    | '/harvests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  EditusersRoute: typeof EditusersRoute
  FeedRoute: typeof FeedRoute
  ForgotRoute: typeof ForgotRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  SignupRoute: typeof SignupRoute
  ClassifierIdRoute: typeof ClassifierIdRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  GroupsJoinRoute: typeof GroupsJoinRoute
  GroupsOwnedRoute: typeof GroupsOwnedRoute
  GroupsParticipatingRoute: typeof GroupsParticipatingRoute
  HarvestsIdRoute: typeof HarvestsIdRoute
  HarvestsCreateRoute: typeof HarvestsCreateRoute
  ClassifierIndexRoute: typeof ClassifierIndexRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  HarvestsIndexRoute: typeof HarvestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editusers': {
      id: '/editusers'
      path: '/editusers'
      fullPath: '/editusers'
      preLoaderRoute: typeof EditusersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harvests/': {
      id: '/harvests/'
      path: '/harvests'
      fullPath: '/harvests'
      preLoaderRoute: typeof HarvestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classifier/': {
      id: '/classifier/'
      path: '/classifier'
      fullPath: '/classifier'
      preLoaderRoute: typeof ClassifierIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harvests/create': {
      id: '/harvests/create'
      path: '/harvests/create'
      fullPath: '/harvests/create'
      preLoaderRoute: typeof HarvestsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harvests/$id': {
      id: '/harvests/$id'
      path: '/harvests/$id'
      fullPath: '/harvests/$id'
      preLoaderRoute: typeof HarvestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/participating': {
      id: '/groups/participating'
      path: '/groups/participating'
      fullPath: '/groups/participating'
      preLoaderRoute: typeof GroupsParticipatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/owned': {
      id: '/groups/owned'
      path: '/groups/owned'
      fullPath: '/groups/owned'
      preLoaderRoute: typeof GroupsOwnedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/join': {
      id: '/groups/join'
      path: '/groups/join'
      fullPath: '/groups/join'
      preLoaderRoute: typeof GroupsJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classifier/$id': {
      id: '/classifier/$id'
      path: '/classifier/$id'
      fullPath: '/classifier/$id'
      preLoaderRoute: typeof ClassifierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  EditusersRoute: EditusersRoute,
  FeedRoute: FeedRoute,
  ForgotRoute: ForgotRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  SignupRoute: SignupRoute,
  ClassifierIdRoute: ClassifierIdRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  GroupsJoinRoute: GroupsJoinRoute,
  GroupsOwnedRoute: GroupsOwnedRoute,
  GroupsParticipatingRoute: GroupsParticipatingRoute,
  HarvestsIdRoute: HarvestsIdRoute,
  HarvestsCreateRoute: HarvestsCreateRoute,
  ClassifierIndexRoute: ClassifierIndexRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  HarvestsIndexRoute: HarvestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
